version: '3'

volumes:
  mongodata:

services:
  mongodb_room_manager:
    image: mongo:4
    container_name: mongodb_room_manager
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=artur
      - MONGODB_ADMIN_PASS=password
      - MONGODB_APPLICATION_DATABASE=sample
      - MONGODB_APPLICATION_USER=aashrey
      - MONGODB_APPLICATION_PASS=admin123

    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - ./:/usr/src/app
      - mongodata:/data/db
    restart: always
    
  rust:
    image: rust:1.65.0
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: cargo run
